### ISSUE TITLE
More tags needed

### ISSUE THREAD

**Issue by Mechalopa** [jayhillx/MysticsBiomes#11]
Additional biomes should be registered in `minecraft:is_overworld` and `minecraft:stronghold_biased_to` biome tags.
Also, I think that autumnal grove and bamboo blossom forest need to be registered in `minecraft:is_forest` biome tag.

**Comment by jayhillx** [comment]
that’s a great idea!! ill make sure to do this in the next update, thanks!

**Comment by Mechalopa** [comment]
I checked 1.20.1-3.1.4 and I think `minecraft:*` is the appropriate namespace for the tag, not `forge`... (sorry for repeating myself)
