### ISSUE TITLE
Strawberry Biome issues

### ISSUE THREAD

**Issue by MajinNina** [jayhillx/MysticsBiomes#12]
I'm on 1.18.2 forge playing with all the mods 7 and it seems that the Strawberry Fields sapling won't grow into it's respective tree but into jacaranda, and the strawberry cows when bred turn into normal cows. Just wondering if there's something I need to do, or if it can be fixed.

**Comment by jayhillx** [comment]
these are all issues resolved in the mods current version, 3.1.6. 1.18.2 will be updated eventually and will contain these fixes.
