### ISSUE TITLE
evil rainbow chickens be looping ticks in here

### ISSUE THREAD

**Issue by nekohacker591** [jayhillx/MysticsBiomes#19]
https://haste.godlike.host/cuvapujule

here is thy server crash log maties beware as chickens dont play nice in servers 

beware the rainbow chicken

my best pirate voice hopefuly that made your day

**Comment by jayhillx** [comment]
hello! i'm so sorry this is happening! im currently working on a quick patch fix to upload tomorrow. for now you could try removing the biomes they can spawn in in the config!

life has felt a little upside down lately, that pirate impression did make me smile so thank you haha!

**Comment by Not-February** [comment]
Hi, I'm also experiencing this on a dedicated server on version 3.1.6.

I'm disabling the rainbow chicken spawns for now, but it is definitely still an issue.

**Comment by jayhillx** [comment]
this issue is now fixed and will be a part of the 3.2 update in march! :)
