### ISSUE TITLE
Config overwrites custom values with default ones for mob spawn parameters on load

### ISSUE THREAD

**Issue by Not-February** [jayhillx/MysticsBiomes#20]
It is this particular parameter in the config I am noticing this problem with:
`["Animal Spawns"]
	"Rainbow Chickens" = ["minecraft:plains", "minecraft:forest", "minecraft:flower_forest"]
`

I have tried completely removing all entries from the array, changing it to just one of the already-included biomes, outright _replacing_ the contents of the list with new entries... but every time, as soon as the server loads up, anything I've done will be overwritten by those same three default values.

This is largely a pressing issue because of https://github.com/jayhillx/MysticsBiomes/issues/19; it means there's currently no in-house way to disable the rainbow chickens causing the server crash.

Versions:

Minecraft 1.20.1
Forge 47.2.0
Mystic's Biomes 3.1.6
Terrablender 3.0.1.4

**Comment by jayhillx** [comment]
thanks for testing and confirming it worked! this will be a part of the 3.2 update in march :)
