### ISSUE TITLE
Strawberry plants are not bonemealable and have no loot table 3.1.6-1.20.1

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [jayhillx/MysticsBiomes#21]
Your Mystic Strawberry plant has an adorable texture, let me start by saying that. 
It doesn't have a loot table, doesn't grow by tickspeed, and isn't bonemealable either. Could these be fixed, please?

**Comment by jayhillx** [comment]
thanks! :)
just like every other crop in game, they don't have a loot table. as of now in the current version they grow slow in biome temps under 0.95. the next update will fix this, and bonemeal will also work on them as well!

**Comment by jayhillx** [comment]
this is now changed in version 3.2 :)
