### ISSUE TITLE
Config resets to default

### ISSUE THREAD

**Issue by niftybottle** [jayhillx/MysticsBiomes#24]
Related to the rainbow chicken problem: I tried removing the possible biomes for the chicken to spawn in as a workaround, but every time I run Minecraft, the config gets reset back to the default, with all the biomes present again. Presumably it doesn't realize the config is there, so creates a fresh copy? I can't say for sure, but it does mean I can't really play with this mod at all on a server, since the workaround doesn't work.

**Comment by jayhillx** [comment]
hey! this is now fixed in version 3.2! :)
