### ISSUE TITLE
Port Mystics Biomes to Fabric:

### ISSUE THREAD

**Issue by saintphaenixos** [jayhillx/MysticsBiomes#30]
Hello,

I love your mod to pieces, and would love to have it on my server, so I'm putting in a formal request for a port to Fabric.

You are amazing and awesome for doing this all for free, so no expectations, I'd just really love to have it there.

**Comment by jayhillx** [comment]
thank you so much, that really means a lot to me! :’) It’s a huge passion project of mine that I think about all the time :)

anywho, I’ve been a little stuck on it lately with all the stuff I want to do. I’m a bit overwhelmed by the idea of working across two different projects in different mod loaders, so if anything I might wait when the final two biomes are added!

**Comment by jayhillx** [comment]
hey there! sorry its been such a long time, i actually ported the mod to fabric 1.20.1 a couple weeks ago! :)
