### ISSUE TITLE
Biomes not showing up properly

### ISSUE THREAD

**Issue by nc0ke** [jayhillx/MysticsBiomes#34]
The trees are like cut on one side. It is like its stuck in a box and it doesn't blend well with the normal world. Some don't even show up. The biomes that don't work properly are --> Lavender Meadow, Bamboo Blossom Forest(sometimes it works, sometimes it doesnt) and Autumnal grove
I tried looking for the biomes but Lavender meadow is not coming out so well. The Bamboo blossom forest and autumnal grove is 
![2024-05-16_22 47 59](https://github.com/jayhillx/MysticsBiomes/assets/170017506/d54b2df2-857f-4223-ae48-8e7f8356de73)
![2024-05-16_22 50 12](https://github.com/jayhillx/MysticsBiomes/assets/170017506/9de04619-d4f7-4a1d-b4f8-94f07a52f76f)
![2024-05-16_22 51 04](https://github.com/jayhillx/MysticsBiomes/assets/170017506/79dd5331-3811-464f-8ee6-6f162a3417fe)

These ones I am not sure if its my own problem but look, one side is like totally cut off
![2024-05-16_23 01 03](https://github.com/jayhillx/MysticsBiomes/assets/170017506/cb14243b-b988-498c-847b-a74eb10f96d5)

**Comment by jayhillx** [comment]
oh geez i've never seen this issue before! sorry this is happening. are you any other biome/world related mods?

**Comment by jayhillx** [comment]
hey there! please reopen this if you still need help with this.
