### ISSUE TITLE
Feature order crash with Regions Unexplored

### ISSUE THREAD

**Issue by Naixatloz** [jayhillx/MysticsBiomes#35]
The new Lagoon biome is causing a feature order crash when Regions Unexplored is also loaded.
[crash-2024-05-18_00.31.51-server.txt](https://github.com/jayhillx/MysticsBiomes/files/15360515/crash-2024-05-18_00.31.51-server.txt)

**Comment by Thunderrock424242** [comment]
i think i also got this same crash 
[latest.log](https://github.com/jayhillx/MysticsBiomes/files/15367026/latest.log)

**Comment by jayhillx** [comment]
hey thank you for reporting this! ill look into this more and see what i can do

**Comment by Thunderrock424242** [comment]
> hey thank you for reporting this! ill look into this more and see what i can do

any updates on this issue?

**Comment by Mrglanet** [comment]
I too have gotten this same crash
[crash-2024-05-25_20.39.28-server.txt](https://github.com/jayhillx/MysticsBiomes/files/15445856/crash-2024-05-25_20.39.28-server.txt)

**Comment by Hanwei233** [comment]
Same issue
https://pastebin.com/tWcZfE1m

**Comment by jayhillx** [comment]
hey everyone, i hope you all get this, i have a bit of an update on this issue! someone amazingly gave me more details to what exactly is causing this and it is fixed now! im planning to release this update next friday on july 12th :)

sorry about the late response!

**Comment by Thunderrock424242** [comment]
No problem thank you.:)

**Comment by jayhillx** [comment]
hey there! this is now fixed in version 3.4 :) https://www.curseforge.com/minecraft/mc-mods/mystics-biomes/files/5527246
