### ISSUE TITLE
Lush Sand blocks cannot be broken faster with tools. Lush Sandstone does not drop. Version 3.3

### ISSUE THREAD

**Issue by WavierPLaines** [jayhillx/MysticsBiomes#36]
Lush Sand blocks cannot be broken faster with tools. Lush Sandstone does not drop. Version 3.3

**Comment by jayhillx** [comment]
thank you for letting me know!

**Comment by jayhillx** [comment]
this is now fixed in the latest version 3.4 ! :) https://www.curseforge.com/minecraft/mc-mods/mystics-biomes/files/5527246
