### ISSUE TITLE
Textures missing in game for rainbow chickens and butterflies (also jacaranda hanging sign)

### ISSUE THREAD

**Issue by ghost** [jayhillx/MysticsBiomes#38]
The textures are located in the mod files, but something about the coding, path, or rendering does not apply the textures to the models, giving them the black and purple squares we all know so well.
Likewise, the item texture for the jacaranda hanging sign is also black and purple. I REALLY wanna see what these silly creatures look like, but for now, I am doomed to the missing textures :,)

**Comment by jayhillx** [comment]
hey there! what version are you using by chance? make sure you're updated to version 3.3.1, i fixed the missing textures in that version

**Comment by ghost** [comment]
Before updating, I was using 3.3. the issue is fixed now in 3.3.1!! thank you, I love this mod btw!!! genuinely squealed when I saw there was peach trees and the biomes are so CUTE. so so so in love with it, you do amazing work!!

**Comment by jayhillx** [comment]
that makes me so happy!! :"D i'm so glad you like it, it truly means a lot to me <33 thank you so much!! :')
