### ISSUE TITLE
1.19.2 red panda lying down missing texture

### ISSUE THREAD

**Issue by zachsai** [jayhillx/MysticsBiomes#4]
![image](https://github.com/jayhillx/MysticsBiomes/assets/63996164/ec9626cb-483a-4755-83af-6e7c77868f70)

**Comment by zachsai** [comment]
![image](https://github.com/jayhillx/MysticsBiomes/assets/63996164/59cb2153-84f4-40dd-839e-c1edb6c1f922)

**Comment by jayhillx** [comment]
fixed in version 3.1.1 on 7.21.23
