### ISSUE TITLE
feature cycle crash with Regions Unexplored mod

### ISSUE THREAD

**Issue by NancalaStarry** [jayhillx/MysticsBiomes#42]
Crash report:
[crash-2024-06-24_17.38.33-server.txt](https://github.com/user-attachments/files/15953275/crash-2024-06-24_17.38.33-server.txt)
I use Cyanide mod for a more detailed report.

Cycle:
At step 9
Feature 'minecraft:kelp_warm'
  must be before 'minecraft:sea_pickle' (defined in 'mysticsbiomes:lagoon' at index 1, 2)
  must be before 'minecraft:kelp_warm' (defined in 'regions_unexplored:rocky_reef' at index 8, 9)

**Comment by jayhillx** [comment]
WOW this is actually insane, i’ll check it out and see if i could get this working this weekend! thank you SO much!

**Comment by Reshy** [comment]
Same problem:  https://pastebin.com/D2azQ5Gb

**Comment by jayhillx** [comment]
hello! this is now fixed in the latest version ! https://www.curseforge.com/minecraft/mc-mods/mystics-biomes/files/5527246
