### ISSUE TITLE
Red Panda's lose textures at night

### ISSUE THREAD

**Issue by Dakimy** [jayhillx/MysticsBiomes#44]
Red Panda's lose texture's once it starts to turn nighttime.
![2024-07-03_00 43 44](https://github.com/jayhillx/MysticsBiomes/assets/174643772/d97ff637-af20-40ef-aa34-51a25916381c)

Daytime does not affect Red Panda's with bugged textures
![2024-07-03_00 44 07](https://github.com/jayhillx/MysticsBiomes/assets/174643772/88b6e4de-5438-4eb9-9a58-52035686148f)

The textures refresh once they are in water.
Sorry I cannot be of much help as I am not good at coding, first noticed when walking around a cherry blossom biome.
On the latest version (version 3.3.1)

**Comment by jayhillx** [comment]
i’m aware of this and it’s fixed, it’ll be in the next update next friday on the 12th :)

**Comment by Dakimy** [comment]
Let's go

**Comment by Dakimy** [comment]
That's good to hear. Can't wait!
