### ISSUE TITLE
[3.4] Vanilla bean transparency is rendered incorrectly

### ISSUE THREAD

**Issue by MoonlitGale** [jayhillx/MysticsBiomes#47]
The transparent pixels in the vanilla bean texture are fully opaque when placed on the sides of blocks; the entire texture is transparent when placed on the bottom of a block.
1.20.1 on Forge 47.1.3. Images were taken in a superflat world that only includes Mystic's Biomes and Terrablender, no performance mods.

![2024-07-12_23 03 01](https://github.com/user-attachments/assets/63775f92-ea68-42b6-aa64-f13cc565b889)
![2024-07-12_23 03 17](https://github.com/user-attachments/assets/f6a02fa0-fa42-4fed-8754-f9e128aafcb9)

**Comment by jayhillx** [comment]
sorry about that! thanks for telling me, it’ll be fixed in the next update in the next couple weeks

**Comment by jayhillx** [comment]
hey there, sorry about the long wait. this has now been fixed in the latest update 3.4.1 :)
