### ISSUE TITLE
Tropical Sapplings grow into jacaranda

### ISSUE THREAD

**Issue by m0thknight** [jayhillx/MysticsBiomes#48]
![2024-07-20_21 37 40](https://github.com/user-attachments/assets/ac2c5c00-94e8-4d39-b071-36daf9156a4c)
![2024-07-20_21 37 46](https://github.com/user-attachments/assets/8f434ffd-c6de-42c4-a6f3-f819c61c8d14)

**Comment by jayhillx** [comment]
hey sorry about the wait, but this is now fixed in the latest version 3.4.1! :)
