### ISSUE TITLE
Latest 1.20.1 Forge version replaces cake's inventory texture with sea foam log

### ISSUE THREAD

**Issue by FluffiKiki** [jayhillx/MysticsBiomes#57]
![image](https://github.com/user-attachments/assets/520ff6c4-4fa2-478f-b0d9-6c02fef8ff76)
![image](https://github.com/user-attachments/assets/9fe29335-c09f-44f3-aa81-53ddecb794c2)

Minecraft 1.20.1, Forge 47.3.0, Mystic's Biomes 3.4.2

Cake's icon appears as top view of sea foam log. Regular cake still appears after placing it. Can this be fixed?

**Comment by jayhillx** [comment]
LOL what on earth that's so random! i just loaded it up to check for myself, and it seemed to be fine for me. i also have a good amount of mods too, i'm really stuck on what could be causing that for you! what mods are you using by chance?

**Comment by FluffiKiki** [comment]
Not a problem, from looking at other packs I've made with this version, I've realized that problem isn't this mod. It only affects the cake texture, too. Here's my mod list, if you happen to know what the issue is. 
![image](https://github.com/user-attachments/assets/d2034ef4-e861-4935-9feb-4c2500bf0132)
![image](https://github.com/user-attachments/assets/7557ef17-5f60-4f6d-8440-0c210ed40c62)
![image](https://github.com/user-attachments/assets/cc991198-9601-42f3-a515-a204cfbf3298)
![image](https://github.com/user-attachments/assets/ea515bd3-8675-46c9-b92a-5f7e01ceae81)
![image](https://github.com/user-attachments/assets/cab51efd-2f73-4541-9e98-9067bd490e7c)

**Comment by FluffiKiki** [comment]
Actually looked into it, the problem came from Create: Food, and it's already been solved. I just never saw the update, lol. On my modpack, it used textures from your mod for some reason. I'll close this since it's solved
