### ISSUE TITLE
No transparent strawberry sapling texture 1.20.1

### ISSUE THREAD

**Issue by unroman** [jayhillx/MysticsBiomes#7]
![image](https://github.com/jayhillx/MysticsBiomes/assets/75941881/71300669-9494-4018-b312-b2ec375dcf66)

**Comment by TelepathicGrunt** [comment]
Seems to affect 1.19.2 as well
![image](https://github.com/jayhillx/MysticsBiomes/assets/40846040/ebe17b15-affc-4436-9226-f47ad0ec50c9)
